---

- debug: var={{ mysql_root_password }}

- include: configure-mysql.yml
  tags: always

# Actually installs MySQL if install_type=='package'
- name: "Install dependencies - Debian"
  include: "dependencies-Debian.yml"
  when: ansible_os_family=='Debian'
  tags: setup

# - name: "Stop mysql if it was installed"
#   command: /etc/init.d/mysql.dpkg-dist stop
#   when: install_mysql|changed
#   tags: setup

- name: Set root user password
  mysql_user: name="root" host="{{ item }}" password="{{ mysql_root_password }}" login_unix_socket="{{ mysql_conf['socket'] }}" check_implicit_admin=yes login_user="root" login_password="{{ mysql_root_password }}"
  with_items:
    - localhost
    - "127.0.0.1"
  tags: always

- name: Setup mysql users
  mysql_user: name="{{ item.user }}" host="{{ item.host }}" password="{{ item.password }}" priv={{ item.grant_pattern }} login_unix_socket="{{ mysql_conf['socket'] }}" check_implicit_admin=yes login_user="root" login_password="{{ mysql_root_password }}"
  with_items: mysql_users
  tags: always
