---

using_upstart: true

logstash_version: 1.4

logstash_user: logstash

logstash_patterns_dir: /opt/opviz/chef-cookbooks/opviz-client/files/default/logstash_patterns

# Default ansible behavior is to replace hashes, not merge. http://docs.ansible.com/intro_configuration.html#hash-behaviour
# So we will assume defaults are overwritten by group vars or playbook vars
logstash:
  rabbitmq:
    host: localhost
    password: ""
  inputs:
    file: {}
    exec: {}
  filters: []

rabbitmq_defaults:
  ssl: "true"
  verify_ssl: "false"
  port: 5671
  user: logstash_external
  exchange: logstash
  exchange_type: direct

